#+TITLE: Manjaro从使用到放弃
#+DATE: <2018-06-30 Sat>
#+TAGS: manjaro, ibus
#+LAYOUT: post
#+CATEGORIES: Linux

这段时间准备把一个老台式机换成Linux系统，然后就准备不在折腾了，慢慢打磨一段时间。在搜索选择发行版的时候发现了[[https://www.manjaro.cn/][欢迎使用Manjaro]]这个网站，看到很多优点，然后就安装了。

#+BEGIN_QUOTE
- 对用户友好、全球排名第1的Linux发行版
- 滚动更新可以使软件保持最新；
- AUR软件仓库有着世界上最齐全的Linux软件
- 丰富的wiki和活跃的社区让所有问题都可以快速得到满意的答案。
#+END_QUOTE
/具体细节大家可以去网站了解/

 #+BEGIN_HTML
 <!--more-->
 #+END_HTML

* 安装过程

烧录U盘、安装系统、整个过程比较流畅，这里确实要说一下比Arch好多了。

*需要注意的地方就是安装系统的时候进度条可能会停住并显示 =Unsquash filesystem= 这个多等一下就好* 开始我以为是系统镜像有问题，又重新做了一遍。

* 系统更新

** 换源

官方的软件源在我这里的网络还是比较慢，需要更换，操作命令如下：

#+BEGIN_SRC sh
sudo pacman-mirrors -i -c China -m rank
#+END_SRC
等一会后会弹出镜像选择对话框，勾选 =http://mirrors.ustc.edu.cn/manjaro/= 并点击两次 =OK= 即可。

具体教程参考[[http://mirrors.ustc.edu.cn/help/manjaro.html][中科大Manjaro源使用帮助]]。

** 更新系统

之前没有用过Arch系列，所以对 =pacman= 命令不熟。这里参考官方wiki [[https://wiki.manjaro.org/index.php?title=Pacman_Overview][Pacman Overview]]，主要命令摘录如下：

#+BEGIN_SRC sh
sudo pacman -Syy        # 换源后更新缓存
sudo pacman -Syyu       # 更新系统
sudo pacman -S base-devel yaourt    # 安装 AUR
sudo reboot    # 重启系统
#+END_SRC

** 放弃原因

前后装了三个不同的桌面系统，分别是 =KDE、LXDE、XFCE= 

下面的内容只是个人的感觉，也是个人遇到的情况，大家可做参考，不涉及系统信仰问题。现在已经过了折腾的年纪，哪个好用，哪个适合自己用哪个。

#+BEGIN_QUOTE
君子生非异也，善假于物也  —— 《劝学》
#+END_QUOTE

*** KDE

- 用这个系统的原因之一是一键安装TIM，而且有AUR软件贼多，并且一条命令搞定
- 安装KDE原因是界面漂亮
- 出现的问题就是：Tim可以安装但是启动一次后就无法再次启动，想想上面网站说的博主用的是lxde，那就换换呗
- 这个没有装中文输入，体验不深


*** LXDE

- 轻量级，家里面的老电脑就是用的lubuntu
- 第一次安装就卡在上面说的那个界面 =Unsquash filesystem= 卡住的时间特长
- 试了几次感觉可能镜像问题，去论坛下载了最新的Beta镜像可以顺利安装
- 因为我一直用Rime输入法，所以就直接安装ibus-rime，安装顺利
- 无法输入中文，又安装了智能拼音，文本编辑器可以使用，但其他应用里面就无法输入了
- 没有继续使用，觉得可能不是官方的版本，支持度不好

*** XFCE

- 安装顺利，界面比lxde好看
- 安装Tim出错，提示就是下载 =deepin-wine-helper= 失败，所以无法 =build=
- 换了两个源都有同样的问题，忘了测试官方源是否可以
- 安装ibus-rime，无法输入中文，因为安装的英文版，我以为字体的原因
- 而且ibus无法随机启动，看了官方wiki，按照相关的设定，但是还是不行
- 安装思源、文泉驿字体，但是依然无法输入中文，继续安装其他的输入方式依然无效

其实这个系统很不错，在排行榜能拿到第一的位置，没两把刷子那是不可能的，软件资源丰富，比如现在特别好用的 =Opera= 浏览器，直接命令安装，其他的操作系统就没这么好的待遇。

不过感觉可能国内用的不多，中文的支持不是太好，英语为母语的国家根本就不需要输入法，而且也不会出现文字乱码啦等等这些乱七八糟的问题，那么这个系统真的是好的选择。

这段时间呢就是想试试这些发行版，看看找一个适合自己的。想找一个不用总是让用户去处理细节问题的系统，适合自己的，尝试代替Windows。
